version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
    rust: latest
  jobs:
    pre_install:
    - maturin build --features python --release

python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .

mkdocs:
  configuration: mkdocs.yml
