version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
    rust: latest

python:
  install:
  - method: pip
    path: .
    requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
